### ISSUE TITLE
Binary is now located under @dylanirlbeck/tailwind-ppx/bin

### ISSUE THREAD

**Issue by gaku-sei** [dylanirlbeck/tailwind-ppx#124]
Since the last release (v0.8.1), the ppx binaries are located under `@dylanirlbeck/tailwind-ppx/bin`, instead of `@dylanirlbeck/tailwind-ppx`. Is it by design? (In which case we might need to update the docs)

**Comment by dylanirlbeck** [comment]
@gaku-sei This is certainly a bug, the `tailwind-ppx` binary should be located via `@dylanirlbeck/tailwind-ppx`. Thanks for reporting!

**Comment by dylanirlbeck** [comment]
Alright the docs are now updated with the correct path to the binary. TLDR the path is now just `tailwind-ppx`.
