### ISSUE TITLE
Postinstall _export not handling existing directory

### ISSUE THREAD

**Issue by JakubMarkiewicz** [dylanirlbeck/tailwind-ppx#130]
Hey,
Sometimes when i deploy app to vercel it happens to crash due to postinstall script not checking, if `_export` directory is already present.

```js

17:00:25.082 | error /vercel/583d5351/node_modules/@dylanirlbeck/tailwind-ppx: Command failed.
-- | --
17:00:25.082 | Exit code: 1
17:00:25.083 | Command: node ./postinstall.js
17:00:25.083 | Arguments:
17:00:25.083 | Directory: /vercel/583d5351/node_modules/@dylanirlbeck/tailwind-ppx
17:00:25.083 | Output:
17:00:25.083 | Could not create _export folder
17:00:25.083 | error: Error: EEXIST: file already exists, mkdir '/vercel/583d5351/node_modules/@dylanirlbeck/tailwind-ppx/3'

```

```js
try {
  fs.mkdirSync('_export');
} catch (e) {
  console.log('Could not create _export folder');
}
```

Maybe we could handle this case by checking if said directory exists and if so, just replacing the binary inside.
I could make a PR

**Comment by vdanchenkov** [comment]
Builds started to fail 3 days ago with exactly the same error.

Local reproduction:
```
cd ./node_modules/@dylanirlbeck/tailwind-ppx/
node ./postinstall.js
```

**Comment by dylanirlbeck** [comment]
Yeah we did change the build process recently. @JakubMarkiewicz I think the fix you mentioned should work, so a PR would be much appreciated!

cc @tatchi since I believe you made these changes.

**Comment by JakubMarkiewicz** [comment]
I've got the working fix but there is one more thing. I've never encountered it during deployment, can't really tell if this is an issue but it definitely is when building locally.
It's the same thing but during esyInstallRelease
```sh
error: Error: EEXIST: file already exists, mkdir '/app/node_modules/@dylanirlbeck/tailwind-ppx/3'
```
Removing the file fixes the issue, but I guess there is no way for us to change the behavior of esyInstallRelease?

**Comment by JakubMarkiewicz** [comment]
Esy maintainer confirmed that they are able to make a fix for second problem. I believe this issue can be closed now

**Comment by dylanirlbeck** [comment]
@JakubMarkiewicz Can you try the latest version I released (v0.8.3)? It should include the changes from your latest PR. If that doesn't fix this issue I'll re-open.

**Comment by JakubMarkiewicz** [comment]
I'll key an eye on builds, so far after 2 builds no issue despite having like 4 failed builds earlier today.

**Comment by vdanchenkov** [comment]
Still seeing following build error quite often:

```
error: Error: EEXIST: file already exists, mkdir '/vercel/workpath0/node_modules/@dylanirlbeck/tailwind-ppx/3'
```
