### ISSUE TITLE
How to optionally enable/disable classes

### ISSUE THREAD

**Issue by tcoopman** [dylanirlbeck/tailwind-ppx#48]
Is it possible to enable/disable classes based on some value? Like use `text-blue500` if something is true otherwise `text-gray-500`

**Comment by dylanirlbeck** [comment]
Hi @tcoopman ! The proper way to do that would be with [`re-classnames`](https://github.com/MinimaHQ/re-classnames) and the `Cn.ifTrue` function. To integrate this with `tailwind-ppx`, you'd want to do the following (let me know if this doesn't work):

```reason
module SomeComponent = {
  [@react.component]
  let make = (~someBool) => {
    let className =
      Cn.make([
        [%tw "text-blue-500"]->Cn.ifTrue(someBool),
        [%tw "text-gray-500"]->Cn.ifTrue(!someBool),
      ]);
    <div className />;
  };
};
```
