### ISSUE TITLE
Use the css-parser OPAM package

### ISSUE THREAD

**Issue by dylanirlbeck** [dylanirlbeck/tailwind-ppx#51]
I completely duplicated the CSS parser code between my repo and `ocaml-css-parser`, so instead I shoud be using it as a dependency from OPAM (see [this comment](https://github.com/astrada/ocaml-css-parser/issues/5#issuecomment-620770145)).

**Comment by azkane** [comment]
Do you need help with this? I could take a shot at if if you want.

**Comment by dylanirlbeck** [comment]
@azkane PRs are definitely welcome! I'd hope this would be a straightforward conversion, since the code is the same (you'll be able to remove any parser/lexer files from the `tailwind-ppx` code). The opam package name is `css-parser`.

Let me know if you need any help! I'll _tentatively_ assign this issue to you, though there is no rush to work on it.

**Comment by dylanirlbeck** [comment]
Closing this for now, since the parser uses OCaml v4.09 (or similar) while `tailwind-ppx` uses 4.06 (consistent with BuckleScript). If someone wants to tackle this in the future, then go ahead, but we should try to avoid bumping the Ocaml version unless absolutely necessary (imo).
