### ISSUE TITLE
Responsive utility not yet supported ? 

### ISSUE THREAD

**Issue by sync** [dylanirlbeck/tailwind-ppx#53]
Thanks a ton for working on this it's wonderful. I've just noticed that `sm:` and friends weren't supported is that right ? 

https://tailwindcss.com/docs/responsive-design/#app

<img width="1025" alt="Screen Shot 2020-04-29 at 1 25 54 pm" src="https://user-images.githubusercontent.com/21725/80558321-4e443900-8a1d-11ea-95ec-13b714c5aafa.png">

**Comment by dylanirlbeck** [comment]
If the class name shows up in your `tailwind.css` file, it should get found. Can you double-check your generated `tailwind.css` file has the following:

```css
.sm\:text-5xl {
   font-size: 3rem;
}
```

I'll investigate this a bit further, and add a test or two for responsive utilities.

**Comment by dylanirlbeck** [comment]
So on my end I'm not able to get responsive utilities to work (even though they're in the `tailwind.css`), so I'll investigate this further. Thanks for bringing up this issue!

**Comment by dylanirlbeck** [comment]
@sync Can you double-check if you're still getting this issue with `v0.6.2` of `tailwind-ppx`? I just released a new version.

**Comment by sync** [comment]
Will do this in a couple of hours, still early morning in Australia. Thank you so much 😊

**Comment by sync** [comment]
@dylanirlbeck it works thank you :-)
