### ISSUE TITLE
Custom colors don't work

### ISSUE THREAD

**Issue by sync** [dylanirlbeck/tailwind-ppx#60]
<img width="704" alt="Screen Shot 2020-04-30 at 8 17 35 am" src="https://user-images.githubusercontent.com/21725/80652353-11c71a80-8abb-11ea-96cd-376cc75afd8f.png">

```
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: ['./src/**/*.{js,jsx,ts,tsx,re}'],

    // These options are passed through directly to PurgeCSS
    options: {
      whitelist: ['html', 'body'],
      defaultExtractor: require('@dylanirlbeck/tailwind-ppx').extractor,
    },
  },
  theme: {
    fontFamily: {
      sans: [
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    extend: {
      colors: {
        blue: {
          ...colors.blue,
          homepass: '#03a9f4',
        },
      },
      zIndex: {
        ...zIndex,
        '-10': '-10',
      },
    },
  },
  variants: {
    backgroundColor: ['responsive', 'hover', 'focus', 'active'],
  },
  plugins: [],
};

```

**Comment by azkane** [comment]
Hey!

Are you using the example code for rebuilding the tailwind.css file that is in the [readme](https://github.com/dylanirlbeck/tailwind-ppx#moving-or-changing-your-tailwindcss-file)? 

I had an issue with it using a custom tailwind config, it seems that the `tailwindcss` command is run in the bucklescript distribution directory (ignoring the config file), I had to define it like this for it to work (in bsconfig.json):
```
"command": "tailwindcss build $in -o $out -c ../../tailwind.config.js"
```
you can find from what directory the build process is running the `tailwindcss` command with something like this, (it should print it in the output of the build)
```
"command": "echo $$(pwd) && tailwindcss build $in -o $out -c ../../tailwind.config.js"
```

The example you posted is working for me with said configuration:
![test](https://user-images.githubusercontent.com/3322582/80653722-64172580-8a40-11ea-8d15-8f15bc00c3d6.png)

**Comment by dylanirlbeck** [comment]
@sync Custom colors should work, since `tailwind-ppx` only knows about whatever `tailwind.css` file you provide it (and implicitly knows about your `tailwind.config.js` if `tailwind.css` has been generated properly). Please take a look at @azkane 's comment as well, as that may provide some insight.

@azkane If there is something wrong with the README section on generators can you open a PR? Thanks for responding on this issue!

**Comment by sync** [comment]
cool i'll have a loot at tweaking the tailwind.config.js

**Comment by dylanirlbeck** [comment]
@sync If you could circle back after trying to modify your tailwind config to confirm if this is still an issue I'd appreciate it. Thanks!

**Comment by sync** [comment]
i'll check this soon :-)

**Comment by sync** [comment]
sorry for the late reply all good
