### ISSUE TITLE
.group class of group-hover utility is not being picked up

### ISSUE THREAD

**Issue by azkane** [dylanirlbeck/tailwind-ppx#69]
Hey!

I mentioned this before in #59, the `group-hover:*` classes are working in the latest version (0.6.4) but the `.group` class isn't being detected.

![test](https://user-images.githubusercontent.com/3322582/80847530-aaea5400-8bd5-11ea-8384-de5979852482.png)

The `.group` class is needed in the parent for the `group-hover:*` classes to work.

**Comment by dylanirlbeck** [comment]
Ah yes, very good catch (and great PR!). I did not realize that the `.group` class was needed.
