### ISSUE TITLE
VSCode autocompletion

### ISSUE THREAD

**Issue by celsobonutti** [dylanirlbeck/tailwind-ppx#88]
I know there's support for `tailwind-coc` in Neovim, but is `vscode-tailwindcss` support planned?

I don't have much experience with VSCode extension development, but I'm more than willing to help in whatever I can.

**Comment by dylanirlbeck** [comment]
@celsobonutti Good call! I just opened an issue for this in `vscode-tailwindcss`, so hopefully we can get a response there: https://github.com/bradlc/vscode-tailwindcss/issues/120

If you want an example of how I implemented auto-completion support in `coc-tailwindcss`, see [this PR](https://github.com/iamcco/coc-tailwindcss/pull/28/files). Perhaps it could provide some inspiration to open a PR in `vscode-tailwindcss`?

**Comment by celsobonutti** [comment]
@dylanirlbeck thanks man, I was in doubt if this should be done here or in `vscode-tailwind`.

Thank your very much for showing me your `coc-tailwindcss` PR, I'll try to create one for VSCode ASAP.

**Comment by dylanirlbeck** [comment]
@celsobonutti  Take a look at this comment in `vscode-tailwindcss` by (seemingly) one of the maintainers: https://github.com/bradlc/vscode-tailwindcss/issues/120#issuecomment-631389316.

If you'll be too busy I'd be happy to try and open a PR, though it'd be awesome if you could! VSCode support is definitely a must-have.

**Comment by celsobonutti** [comment]
Hey @dylanirlbeck! I had a hard time this week at my work and couldn't work on that PR.

I'll do it tomorrow or Sunday for sure, 100% agree that VSCode support is a must-have.

**Comment by dylanirlbeck** [comment]
No worries! There's no rush --- let me know if you have any questions or need a code review 😄

**Comment by celsobonutti** [comment]
Hey @dylanirlbeck, I've created a PR: bradlc/vscode-tailwindcss#122

But I'm not able to test the extension at all. I also tried to do some other changes and see if they have any effect, but had no luck. Can you help me with that?

Thank you very much!

**Comment by dylanirlbeck** [comment]
@celsobonutti Did you see [Brad's comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) about the new experimental regex feature? Would be awesome if you could try it out with `tailwind-ppx`! If it works, feel free to open a PR to add a section to the README 😄

**Comment by celsobonutti** [comment]
Hey @dylanirlbeck! I'll do it as soon as I can, thanks for the heads up! 😄

**Comment by dauletisataev** [comment]
Hey! @celsobonutti @dylanirlbeck  so, you decided to stick with `tailwindCSS.experimental.classRegex` ? if yes, it would be very helpful for others to post kinda guideline here :)

**Comment by dauletisataev** [comment]
I have added quick configuration in `settings.json`:
`"tailwindCSS.experimental.classRegex": [
      "%tw \"([^\"]*)"
  ]`
But, it does not cover the cases like this, when string started in new line:
`%tw
"top-full left-0"`
